/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goc.Frames;

import goc.Sources.Info;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame(){
        try {
            initComponents();
            
            Info.carregarInformacoes();
            
            String root = new File("..").getCanonicalPath();
            
            if(!(root.equals("C:\\Users\\Admin\\Documents\\NetBeansProjects"))){
                java.io.File caminho = new java.io.File(root + "\\src\\goc\\img\\sdsds.jpg");
                uJPanelImagem1.setImagem(caminho);
            }
            
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2-20);
        } catch (SQLException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public InfoFrame(int CodigoOpiniao) throws IOException {
        initComponents();
        
        String root = new File("..").getCanonicalPath();
        
        if(!(root.equals("C:\\Users\\Admin\\Documents\\NetBeansProjects"))){
            java.io.File caminho = new java.io.File(root + "\\src\\goc\\img\\sdsds.jpg");
            uJPanelImagem1.setImagem(caminho);
        }
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2-20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        buttonInsert = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();
        buttonMenu = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelOfertas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelUnidade = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelAvAtendimento = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelAvVarProd = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelAvQualProd = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelAvPrecos = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelAvFila = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelTema3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelAvAtendCaixa = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labelAvAcougue = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelAvPadaria = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        labelAvFrios = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        labelAvHortifruti = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        labelAvMercearia = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        labelAvLanchonete = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        labelAvAdega = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        labelAvPegpese = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        labelEncontrou = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelProdProcura = new javax.swing.JTextArea();
        labelAvisar = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        labelTipoComentario = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        labelComentario = new javax.swing.JTextArea();
        checkRespondido = new javax.swing.JCheckBox();
        checkAcompanhar = new javax.swing.JCheckBox();
        checkImportante = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        labelAvEstacionamento = new javax.swing.JLabel();
        labelTema1 = new javax.swing.JLabel();
        labelTema2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        setUndecorated(true);
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\GOC\\src\\goc\\img\\sdsds.jpg"));
        uJPanelImagem1.setMaximumSize(new java.awt.Dimension(800, 650));
        uJPanelImagem1.setMinimumSize(new java.awt.Dimension(800, 650));
        uJPanelImagem1.setPreferredSize(new java.awt.Dimension(800, 650));
        uJPanelImagem1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonInsert.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        buttonInsert.setText("Inserir outra opinião");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 595, 150, 40));

        buttonView.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        buttonView.setText("Visualizar opiniões");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 595, 150, 40));

        buttonMenu.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        buttonMenu.setText("Menu Principal");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 595, 150, 40));

        labelNome.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(240, 255, 240));
        labelNome.setText("Lorem Ipsum Dolor");
        labelNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 260, 30));

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 255, 240));
        jLabel2.setText("Nome");
        uJPanelImagem1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        labelEmail.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(240, 255, 240));
        labelEmail.setText("Lorem Ipsum Dolor");
        labelEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 30));

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 255, 240));
        jLabel4.setText("Email");
        uJPanelImagem1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        labelOfertas.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelOfertas.setForeground(new java.awt.Color(240, 255, 240));
        labelOfertas.setText("Não");
        labelOfertas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelOfertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, 20));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 255, 240));
        jLabel6.setText("Telefone");
        uJPanelImagem1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 30));

        labelData.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelData.setForeground(new java.awt.Color(240, 255, 240));
        labelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelData.setText("00/00/0000");
        labelData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, 30));

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 255, 240));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Data");
        uJPanelImagem1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, 30));

        jLabel9.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Receber ofertas por email?");
        uJPanelImagem1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, 20));

        labelTelefone.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(240, 255, 240));
        labelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefone.setText("3224-4000");
        labelTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 30));

        labelUnidade.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelUnidade.setForeground(new java.awt.Color(240, 255, 240));
        labelUnidade.setText("São Bernardo do Campo");
        labelUnidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 20));

        jLabel12.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Temas");
        uJPanelImagem1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 50, 20));

        labelAvAtendimento.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvAtendimento.setForeground(new java.awt.Color(240, 255, 240));
        labelAvAtendimento.setText("Não avaliado");
        labelAvAtendimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, 20));

        jLabel14.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Atendimento");
        uJPanelImagem1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 20));

        labelAvVarProd.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvVarProd.setForeground(new java.awt.Color(240, 255, 240));
        labelAvVarProd.setText("Não avaliado");
        labelAvVarProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvVarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 110, 20));

        jLabel16.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Variedade dos Produtos");
        uJPanelImagem1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 20));

        labelAvQualProd.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvQualProd.setForeground(new java.awt.Color(240, 255, 240));
        labelAvQualProd.setText("Não avaliado");
        labelAvQualProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvQualProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 110, 20));

        jLabel18.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Qualidade dos Produtos");
        uJPanelImagem1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 20));

        labelAvPrecos.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvPrecos.setForeground(new java.awt.Color(240, 255, 240));
        labelAvPrecos.setText("Não avaliado");
        labelAvPrecos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvPrecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 110, 20));

        jLabel20.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Preços");
        uJPanelImagem1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 160, 20));

        labelAvFila.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvFila.setForeground(new java.awt.Color(240, 255, 240));
        labelAvFila.setText("Não avaliado");
        labelAvFila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, 20));

        jLabel22.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fila");
        uJPanelImagem1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 20));

        labelTema3.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelTema3.setForeground(new java.awt.Color(240, 255, 240));
        labelTema3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelTema3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 320, 20));

        jLabel24.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Estacionamento");
        uJPanelImagem1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 160, 20));

        labelAvAtendCaixa.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvAtendCaixa.setForeground(new java.awt.Color(240, 255, 240));
        labelAvAtendCaixa.setText("Não avaliado");
        labelAvAtendCaixa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvAtendCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 110, 20));

        jLabel26.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Atendimento do Caixa");
        uJPanelImagem1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 20));

        labelAvAcougue.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvAcougue.setForeground(new java.awt.Color(240, 255, 240));
        labelAvAcougue.setText("Não avaliado");
        labelAvAcougue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvAcougue, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 110, 20));

        jLabel28.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Açougue");
        uJPanelImagem1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, 20));

        labelAvPadaria.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvPadaria.setForeground(new java.awt.Color(240, 255, 240));
        labelAvPadaria.setText("Não avaliado");
        labelAvPadaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvPadaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 110, 20));

        jLabel30.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Padaria");
        uJPanelImagem1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 160, 20));

        labelAvFrios.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvFrios.setForeground(new java.awt.Color(240, 255, 240));
        labelAvFrios.setText("Não avaliado");
        labelAvFrios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvFrios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, 20));

        jLabel32.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Frios");
        uJPanelImagem1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 160, 20));

        labelAvHortifruti.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvHortifruti.setForeground(new java.awt.Color(240, 255, 240));
        labelAvHortifruti.setText("Não avaliado");
        labelAvHortifruti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvHortifruti, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 110, 20));

        jLabel34.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Hortifruti");
        uJPanelImagem1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 160, 20));

        labelAvMercearia.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvMercearia.setForeground(new java.awt.Color(240, 255, 240));
        labelAvMercearia.setText("Não avaliado");
        labelAvMercearia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvMercearia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 110, 20));

        jLabel36.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Mercearia");
        uJPanelImagem1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 20));

        labelAvLanchonete.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvLanchonete.setForeground(new java.awt.Color(240, 255, 240));
        labelAvLanchonete.setText("Não avaliado");
        labelAvLanchonete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvLanchonete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 110, 20));

        jLabel38.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Lanchonete");
        uJPanelImagem1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 160, 20));

        labelAvAdega.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvAdega.setForeground(new java.awt.Color(240, 255, 240));
        labelAvAdega.setText("Não avaliado");
        labelAvAdega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvAdega, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 110, 20));

        jLabel40.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Adega");
        uJPanelImagem1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 160, 20));

        labelAvPegpese.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvPegpese.setForeground(new java.awt.Color(240, 255, 240));
        labelAvPegpese.setText("Não avaliado");
        labelAvPegpese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvPegpese, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 110, 20));

        jLabel42.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Pegpese (Ambiente Geral)");
        uJPanelImagem1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 160, 20));

        labelEncontrou.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelEncontrou.setForeground(new java.awt.Color(240, 255, 240));
        labelEncontrou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEncontrou.setText("Não respondeu");
        labelEncontrou.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelEncontrou, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 110, 20));

        jLabel44.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Você encontrou o que procurava?");
        uJPanelImagem1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 200, 20));

        jLabel46.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Se a resposta for \"Não\" diga-nos que procurava:");
        uJPanelImagem1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 380, 20));

        labelProdProcura.setEditable(false);
        labelProdProcura.setColumns(20);
        labelProdProcura.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        labelProdProcura.setLineWrap(true);
        labelProdProcura.setRows(5);
        labelProdProcura.setWrapStyleWord(true);
        labelProdProcura.setFocusable(false);
        jScrollPane2.setViewportView(labelProdProcura);

        uJPanelImagem1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 380, 120));

        labelAvisar.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelAvisar.setForeground(new java.awt.Color(240, 255, 240));
        labelAvisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvisar.setText("Não");
        labelAvisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 80, 30));

        jLabel47.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Avisar quando o produto chegar?");
        uJPanelImagem1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 200, 30));

        labelTipoComentario.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        labelTipoComentario.setForeground(new java.awt.Color(240, 255, 240));
        labelTipoComentario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoComentario.setText("Sem comentário");
        labelTipoComentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelTipoComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 120, 30));

        jLabel49.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Tipo do comentário:");
        uJPanelImagem1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 120, 30));

        labelComentario.setEditable(false);
        labelComentario.setColumns(20);
        labelComentario.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        labelComentario.setLineWrap(true);
        labelComentario.setRows(5);
        labelComentario.setWrapStyleWord(true);
        labelComentario.setFocusable(false);
        jScrollPane3.setViewportView(labelComentario);

        uJPanelImagem1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 380, 160));

        checkRespondido.setBackground(new java.awt.Color(0, 153, 51));
        checkRespondido.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        checkRespondido.setForeground(new java.awt.Color(255, 255, 255));
        checkRespondido.setText("Respondido");
        checkRespondido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkRespondidoItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(checkRespondido, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 540, -1, -1));

        checkAcompanhar.setBackground(new java.awt.Color(204, 204, 0));
        checkAcompanhar.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        checkAcompanhar.setText("Acompanhar");
        checkAcompanhar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkAcompanharItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(checkAcompanhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        checkImportante.setBackground(new java.awt.Color(208, 0, 0));
        checkImportante.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        checkImportante.setForeground(new java.awt.Color(255, 255, 255));
        checkImportante.setText("Importante");
        checkImportante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkImportanteItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(checkImportante, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Unidade");
        uJPanelImagem1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 70, 20));

        labelAvEstacionamento.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelAvEstacionamento.setForeground(new java.awt.Color(240, 255, 240));
        labelAvEstacionamento.setText("Não avaliado");
        labelAvEstacionamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        uJPanelImagem1.add(labelAvEstacionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 110, 20));

        labelTema1.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelTema1.setForeground(new java.awt.Color(240, 255, 240));
        labelTema1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        labelTema1.setNextFocusableComponent(labelTema2);
        uJPanelImagem1.add(labelTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 320, 20));

        labelTema2.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        labelTema2.setForeground(new java.awt.Color(240, 255, 240));
        labelTema2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        labelTema2.setNextFocusableComponent(labelTema3);
        uJPanelImagem1.add(labelTema2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        try {
            new MenuFrame().setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMenuActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        Info.carregarView();
        this.dispose();
    }//GEN-LAST:event_buttonViewActionPerformed

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        Info.abrirInserir();
        this.dispose();
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void checkAcompanharItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkAcompanharItemStateChanged
        try {
            Info.update_tags();
        } catch (SQLException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkAcompanharItemStateChanged

    private void checkImportanteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkImportanteItemStateChanged
        try {
            Info.update_tags();
        } catch (SQLException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkImportanteItemStateChanged

    private void checkRespondidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRespondidoItemStateChanged
        try {
            Info.update_tags();
        } catch (SQLException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkRespondidoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonInsert;
    public static javax.swing.JButton buttonMenu;
    public static javax.swing.JButton buttonView;
    public static javax.swing.JCheckBox checkAcompanhar;
    public static javax.swing.JCheckBox checkImportante;
    public static javax.swing.JCheckBox checkRespondido;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel28;
    public static javax.swing.JLabel jLabel30;
    public static javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel38;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel40;
    public static javax.swing.JLabel jLabel42;
    public static javax.swing.JLabel jLabel44;
    public static javax.swing.JLabel jLabel46;
    public static javax.swing.JLabel jLabel47;
    public static javax.swing.JLabel jLabel49;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel labelAvAcougue;
    public static javax.swing.JLabel labelAvAdega;
    public static javax.swing.JLabel labelAvAtendCaixa;
    public static javax.swing.JLabel labelAvAtendimento;
    public static javax.swing.JLabel labelAvEstacionamento;
    public static javax.swing.JLabel labelAvFila;
    public static javax.swing.JLabel labelAvFrios;
    public static javax.swing.JLabel labelAvHortifruti;
    public static javax.swing.JLabel labelAvLanchonete;
    public static javax.swing.JLabel labelAvMercearia;
    public static javax.swing.JLabel labelAvPadaria;
    public static javax.swing.JLabel labelAvPegpese;
    public static javax.swing.JLabel labelAvPrecos;
    public static javax.swing.JLabel labelAvQualProd;
    public static javax.swing.JLabel labelAvVarProd;
    public static javax.swing.JLabel labelAvisar;
    public static javax.swing.JTextArea labelComentario;
    public static javax.swing.JLabel labelData;
    public static javax.swing.JLabel labelEmail;
    public static javax.swing.JLabel labelEncontrou;
    public static javax.swing.JLabel labelNome;
    public static javax.swing.JLabel labelOfertas;
    public static javax.swing.JTextArea labelProdProcura;
    public static javax.swing.JLabel labelTelefone;
    public static javax.swing.JLabel labelTema1;
    public static javax.swing.JLabel labelTema2;
    public static javax.swing.JLabel labelTema3;
    public static javax.swing.JLabel labelTipoComentario;
    public static javax.swing.JLabel labelUnidade;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
