/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goc.Frames;

import goc.Sources.Inserir;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class InserirFrame extends javax.swing.JFrame {

    /**
     * Creates new form Inserir_Papel
     * @throws java.io.IOException
     */
        
    public InserirFrame() throws IOException, SQLException {
        initComponents();
        
        String root = new File("..").getCanonicalPath();
        
        if(!(root.equals("C:\\Users\\Admin\\Documents\\NetBeansProjects"))){
            java.io.File caminho = new java.io.File(root + "\\src\\goc\\img\\sdsds.jpg");
            uJPanelImagem1.setImagem(caminho);
        }
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2-20);
        
        Inserir.carregarTemas();
        Inserir.carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsfeed = new javax.swing.ButtonGroup();
        Atendimento = new javax.swing.ButtonGroup();
        VariedadeProdutos = new javax.swing.ButtonGroup();
        QualidadeProdutos = new javax.swing.ButtonGroup();
        Precos = new javax.swing.ButtonGroup();
        Fila = new javax.swing.ButtonGroup();
        Estacionamento = new javax.swing.ButtonGroup();
        AtendimentoCaixa = new javax.swing.ButtonGroup();
        Acougue = new javax.swing.ButtonGroup();
        Padaria = new javax.swing.ButtonGroup();
        Frios = new javax.swing.ButtonGroup();
        Hortifruti = new javax.swing.ButtonGroup();
        Mercearia = new javax.swing.ButtonGroup();
        Lanchonete = new javax.swing.ButtonGroup();
        Adega = new javax.swing.ButtonGroup();
        Pegpese = new javax.swing.ButtonGroup();
        EncontrouProduto = new javax.swing.ButtonGroup();
        AvisoProduto = new javax.swing.ButtonGroup();
        TipoComentario = new javax.swing.ButtonGroup();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFone = new javax.swing.JTextField();
        TextNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextData = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        EmailNao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        EmailSim = new javax.swing.JRadioButton();
        ComentElogio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        OtimoAtendimento = new javax.swing.JRadioButton();
        OtimoQualProd = new javax.swing.JRadioButton();
        OtimoVarProd = new javax.swing.JRadioButton();
        OtimoPrecos = new javax.swing.JRadioButton();
        OtimoFila = new javax.swing.JRadioButton();
        OtimoEstacionamento = new javax.swing.JRadioButton();
        OtimoAtendCaixa = new javax.swing.JRadioButton();
        OtimoPadaria = new javax.swing.JRadioButton();
        OtimoAcougue = new javax.swing.JRadioButton();
        OtimoFrios = new javax.swing.JRadioButton();
        OtimoHortifruti = new javax.swing.JRadioButton();
        OtimoMercearia = new javax.swing.JRadioButton();
        OtimoLanchonete = new javax.swing.JRadioButton();
        OtimoPegpese = new javax.swing.JRadioButton();
        BomAtendimento = new javax.swing.JRadioButton();
        BomQualProd = new javax.swing.JRadioButton();
        BomVarProd = new javax.swing.JRadioButton();
        BomPrecos = new javax.swing.JRadioButton();
        BomFila = new javax.swing.JRadioButton();
        BomEstacionamento = new javax.swing.JRadioButton();
        BomAtendCaixa = new javax.swing.JRadioButton();
        BomPadaria = new javax.swing.JRadioButton();
        BomAcougue = new javax.swing.JRadioButton();
        BomFrios = new javax.swing.JRadioButton();
        BomHortifruti = new javax.swing.JRadioButton();
        BomMercearia = new javax.swing.JRadioButton();
        BomLanchonete = new javax.swing.JRadioButton();
        BomPegpese = new javax.swing.JRadioButton();
        RegularAtendimento = new javax.swing.JRadioButton();
        RegularQualProd = new javax.swing.JRadioButton();
        RegularVarProd = new javax.swing.JRadioButton();
        RegularPrecos = new javax.swing.JRadioButton();
        RegularFila = new javax.swing.JRadioButton();
        RegularEstacionamento = new javax.swing.JRadioButton();
        RegularAtendCaixa = new javax.swing.JRadioButton();
        RegularPadaria = new javax.swing.JRadioButton();
        RegularAcougue = new javax.swing.JRadioButton();
        RegularFrios = new javax.swing.JRadioButton();
        RegularHortifruti = new javax.swing.JRadioButton();
        RegularMercearia = new javax.swing.JRadioButton();
        RegularLanchonete = new javax.swing.JRadioButton();
        RegularPegpese = new javax.swing.JRadioButton();
        RuimAtendimento = new javax.swing.JRadioButton();
        RuimQualProd = new javax.swing.JRadioButton();
        RuimVarProd = new javax.swing.JRadioButton();
        RuimPrecos = new javax.swing.JRadioButton();
        RuimFila = new javax.swing.JRadioButton();
        RuimEstacionamento = new javax.swing.JRadioButton();
        RuimAtendCaixa = new javax.swing.JRadioButton();
        RuimPadaria = new javax.swing.JRadioButton();
        RuimAcougue = new javax.swing.JRadioButton();
        RuimFrios = new javax.swing.JRadioButton();
        RuimHortifruti = new javax.swing.JRadioButton();
        RuimMercearia = new javax.swing.JRadioButton();
        RuimLanchonete = new javax.swing.JRadioButton();
        RuimPegpese = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        EncontrouNao = new javax.swing.JRadioButton();
        EncontrouSim = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Comentario = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        AvisarNao = new javax.swing.JRadioButton();
        AvisarSim = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ComentSugestao = new javax.swing.JRadioButton();
        ComentReclamacao = new javax.swing.JRadioButton();
        ComentDuvida = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProcuraProduto = new javax.swing.JTextArea();
        buttonSalvar = new javax.swing.JButton();
        Unidade = new javax.swing.JComboBox<>();
        AnonimoCheck = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        OtimoAdega = new javax.swing.JRadioButton();
        BomAdega = new javax.swing.JRadioButton();
        RegularAdega = new javax.swing.JRadioButton();
        RuimAdega = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        Origem_OP = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTemasS = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaTemasDB = new javax.swing.JList<>();
        buttonEsquerda = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        buttonDireita = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        buttonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setUndecorated(true);
        setResizable(false);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 35, 35));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uJPanelImagem1.setBackground(new java.awt.Color(0, 0, 0));
        uJPanelImagem1.setForeground(new java.awt.Color(255, 30, 30));
        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\GOC\\src\\goc\\img\\sdsds.jpg"));
        uJPanelImagem1.setPreferredSize(new java.awt.Dimension(800, 700));
        uJPanelImagem1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G    C");
        uJPanelImagem1.add(jLabel1);
        jLabel1.setBounds(330, 20, 170, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/logo.png"))); // NOI18N
        uJPanelImagem1.add(jLabel3);
        jLabel3.setBounds(390, 10, 60, 81);

        buttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/icoBack.png"))); // NOI18N
        buttonVoltar.setBorderPainted(false);
        buttonVoltar.setContentAreaFilled(false);
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonVoltar);
        buttonVoltar.setBounds(10, 35, 48, 48);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 212, 90));
        jLabel2.setText("Unidade:");
        uJPanelImagem1.add(jLabel2);
        jLabel2.setBounds(20, 240, 54, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 212, 90));
        jLabel4.setText("Data");
        uJPanelImagem1.add(jLabel4);
        jLabel4.setBounds(230, 160, 40, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qualidade dos produtos");
        uJPanelImagem1.add(jLabel5);
        jLabel5.setBounds(20, 370, 150, 16);

        TextFone.setBackground(new java.awt.Color(230, 255, 226));
        TextFone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextFone.setNextFocusableComponent(TextData);
        uJPanelImagem1.add(TextFone);
        TextFone.setBounds(70, 160, 150, 20);

        TextNome.setBackground(new java.awt.Color(230, 255, 226));
        TextNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextNome.setNextFocusableComponent(TextEmail);
        uJPanelImagem1.add(TextNome);
        TextNome.setBounds(70, 120, 320, 16);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(138, 212, 90));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Origem da Opinião");
        uJPanelImagem1.add(jLabel6);
        jLabel6.setBounds(610, 35, 170, 20);

        TextData.setBackground(new java.awt.Color(232, 237, 220));
        try {
            TextData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextData.setNextFocusableComponent(AnonimoCheck);
        TextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(TextData);
        TextData.setBounds(270, 160, 120, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(138, 212, 90));
        jLabel7.setText("Fone:");
        uJPanelImagem1.add(jLabel7);
        jLabel7.setBounds(20, 160, 50, 20);

        EmailNao.setBackground(new java.awt.Color(232, 237, 220));
        newsfeed.add(EmailNao);
        EmailNao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EmailNao.setForeground(new java.awt.Color(232, 237, 220));
        EmailNao.setText("Não");
        EmailNao.setActionCommand("0");
        EmailNao.setContentAreaFilled(false);
        EmailNao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EmailNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailNaoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(EmailNao);
        EmailNao.setBounds(340, 207, 50, 20);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(138, 212, 90));
        jLabel8.setText("E-mail:");
        uJPanelImagem1.add(jLabel8);
        jLabel8.setBounds(20, 140, 50, 20);

        EmailSim.setBackground(new java.awt.Color(232, 237, 220));
        newsfeed.add(EmailSim);
        EmailSim.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EmailSim.setForeground(new java.awt.Color(232, 237, 220));
        EmailSim.setText("Sim");
        EmailSim.setActionCommand("1");
        EmailSim.setContentAreaFilled(false);
        EmailSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EmailSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailSimActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(EmailSim);
        EmailSim.setBounds(290, 207, 47, 20);

        ComentElogio.setBackground(new java.awt.Color(232, 237, 220));
        TipoComentario.add(ComentElogio);
        ComentElogio.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        ComentElogio.setForeground(new java.awt.Color(232, 237, 220));
        ComentElogio.setText("Elogios");
        ComentElogio.setActionCommand("4");
        ComentElogio.setBorder(null);
        ComentElogio.setContentAreaFilled(false);
        ComentElogio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ComentElogio.setNextFocusableComponent(Comentario);
        ComentElogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentElogioActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(ComentElogio);
        ComentElogio.setBounds(700, 340, 90, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(138, 212, 90));
        jLabel9.setText("Gostaria de receber nossas ofertas por email?");
        uJPanelImagem1.add(jLabel9);
        jLabel9.setBounds(20, 210, 280, 17);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(138, 212, 90));
        jLabel10.setText("Avaliação Setores");
        uJPanelImagem1.add(jLabel10);
        jLabel10.setBounds(20, 480, 140, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REGULAR");
        uJPanelImagem1.add(jLabel11);
        jLabel11.setBounds(290, 300, 50, 16);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Atendimento");
        uJPanelImagem1.add(jLabel12);
        jLabel12.setBounds(20, 330, 150, 16);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Variedade de produtos");
        uJPanelImagem1.add(jLabel13);
        jLabel13.setBounds(20, 350, 150, 16);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Atendimento do Caixa");
        uJPanelImagem1.add(jLabel14);
        jLabel14.setBounds(20, 450, 150, 16);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Preços");
        uJPanelImagem1.add(jLabel15);
        jLabel15.setBounds(20, 390, 150, 16);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fila");
        uJPanelImagem1.add(jLabel16);
        jLabel16.setBounds(20, 410, 150, 16);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Estacionamento");
        uJPanelImagem1.add(jLabel17);
        jLabel17.setBounds(20, 430, 150, 16);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Frios");
        uJPanelImagem1.add(jLabel18);
        jLabel18.setBounds(20, 560, 150, 16);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Açougue");
        uJPanelImagem1.add(jLabel19);
        jLabel19.setBounds(20, 520, 150, 16);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Padaria");
        uJPanelImagem1.add(jLabel20);
        jLabel20.setBounds(20, 540, 150, 16);

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Pegpese (Ambiente Geral)");
        uJPanelImagem1.add(jLabel21);
        jLabel21.setBounds(20, 660, 150, 16);

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Hortifruti");
        uJPanelImagem1.add(jLabel22);
        jLabel22.setBounds(20, 580, 150, 16);

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mercearia");
        uJPanelImagem1.add(jLabel23);
        jLabel23.setBounds(20, 600, 150, 16);

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Lanchonete");
        uJPanelImagem1.add(jLabel24);
        jLabel24.setBounds(20, 620, 150, 16);

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ÓTIMO");
        uJPanelImagem1.add(jLabel25);
        jLabel25.setBounds(190, 300, 40, 16);

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("BOM");
        uJPanelImagem1.add(jLabel26);
        jLabel26.setBounds(250, 300, 40, 16);

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("RUIM");
        uJPanelImagem1.add(jLabel27);
        jLabel27.setBounds(352, 300, 40, 16);

        OtimoAtendimento.setBackground(new java.awt.Color(50, 169, 107));
        Atendimento.add(OtimoAtendimento);
        OtimoAtendimento.setActionCommand("4");
        OtimoAtendimento.setBorder(null);
        OtimoAtendimento.setContentAreaFilled(false);
        OtimoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtimoAtendimentoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(OtimoAtendimento);
        OtimoAtendimento.setBounds(200, 330, 20, 13);

        OtimoQualProd.setBackground(new java.awt.Color(50, 169, 107));
        QualidadeProdutos.add(OtimoQualProd);
        OtimoQualProd.setActionCommand("4");
        OtimoQualProd.setBorder(null);
        OtimoQualProd.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoQualProd);
        OtimoQualProd.setBounds(200, 370, 20, 13);

        OtimoVarProd.setBackground(new java.awt.Color(50, 169, 107));
        VariedadeProdutos.add(OtimoVarProd);
        OtimoVarProd.setActionCommand("4");
        OtimoVarProd.setBorder(null);
        OtimoVarProd.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoVarProd);
        OtimoVarProd.setBounds(200, 350, 20, 13);

        OtimoPrecos.setBackground(new java.awt.Color(50, 169, 107));
        Precos.add(OtimoPrecos);
        OtimoPrecos.setActionCommand("4");
        OtimoPrecos.setBorder(null);
        OtimoPrecos.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoPrecos);
        OtimoPrecos.setBounds(200, 390, 20, 13);

        OtimoFila.setBackground(new java.awt.Color(50, 169, 107));
        Fila.add(OtimoFila);
        OtimoFila.setActionCommand("4");
        OtimoFila.setBorder(null);
        OtimoFila.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoFila);
        OtimoFila.setBounds(200, 410, 20, 13);

        OtimoEstacionamento.setBackground(new java.awt.Color(50, 169, 107));
        Estacionamento.add(OtimoEstacionamento);
        OtimoEstacionamento.setActionCommand("4");
        OtimoEstacionamento.setBorder(null);
        OtimoEstacionamento.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoEstacionamento);
        OtimoEstacionamento.setBounds(200, 430, 20, 13);

        OtimoAtendCaixa.setBackground(new java.awt.Color(50, 169, 107));
        AtendimentoCaixa.add(OtimoAtendCaixa);
        OtimoAtendCaixa.setActionCommand("4");
        OtimoAtendCaixa.setBorder(null);
        OtimoAtendCaixa.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoAtendCaixa);
        OtimoAtendCaixa.setBounds(200, 450, 20, 13);

        OtimoPadaria.setBackground(new java.awt.Color(50, 169, 107));
        Padaria.add(OtimoPadaria);
        OtimoPadaria.setActionCommand("4");
        OtimoPadaria.setBorder(null);
        OtimoPadaria.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoPadaria);
        OtimoPadaria.setBounds(200, 540, 20, 13);

        OtimoAcougue.setBackground(new java.awt.Color(50, 169, 107));
        Acougue.add(OtimoAcougue);
        OtimoAcougue.setActionCommand("4");
        OtimoAcougue.setBorder(null);
        OtimoAcougue.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoAcougue);
        OtimoAcougue.setBounds(200, 520, 20, 13);

        OtimoFrios.setBackground(new java.awt.Color(50, 169, 107));
        Frios.add(OtimoFrios);
        OtimoFrios.setActionCommand("4");
        OtimoFrios.setBorder(null);
        OtimoFrios.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoFrios);
        OtimoFrios.setBounds(200, 560, 20, 13);

        OtimoHortifruti.setBackground(new java.awt.Color(50, 169, 107));
        Hortifruti.add(OtimoHortifruti);
        OtimoHortifruti.setActionCommand("4");
        OtimoHortifruti.setBorder(null);
        OtimoHortifruti.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoHortifruti);
        OtimoHortifruti.setBounds(200, 580, 20, 13);

        OtimoMercearia.setBackground(new java.awt.Color(50, 169, 107));
        Mercearia.add(OtimoMercearia);
        OtimoMercearia.setActionCommand("4");
        OtimoMercearia.setBorder(null);
        OtimoMercearia.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoMercearia);
        OtimoMercearia.setBounds(200, 600, 20, 13);

        OtimoLanchonete.setBackground(new java.awt.Color(50, 169, 107));
        Lanchonete.add(OtimoLanchonete);
        OtimoLanchonete.setActionCommand("4");
        OtimoLanchonete.setBorder(null);
        OtimoLanchonete.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoLanchonete);
        OtimoLanchonete.setBounds(200, 620, 20, 13);

        OtimoPegpese.setBackground(new java.awt.Color(50, 169, 107));
        Pegpese.add(OtimoPegpese);
        OtimoPegpese.setActionCommand("4");
        OtimoPegpese.setBorder(null);
        OtimoPegpese.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoPegpese);
        OtimoPegpese.setBounds(200, 660, 20, 13);

        BomAtendimento.setBackground(new java.awt.Color(161, 211, 176));
        Atendimento.add(BomAtendimento);
        BomAtendimento.setForeground(new java.awt.Color(161, 211, 176));
        BomAtendimento.setActionCommand("3");
        BomAtendimento.setBorder(null);
        BomAtendimento.setContentAreaFilled(false);
        BomAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BomAtendimentoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(BomAtendimento);
        BomAtendimento.setBounds(255, 330, 20, 13);

        BomQualProd.setBackground(new java.awt.Color(161, 211, 176));
        QualidadeProdutos.add(BomQualProd);
        BomQualProd.setForeground(new java.awt.Color(161, 211, 176));
        BomQualProd.setActionCommand("3");
        BomQualProd.setBorder(null);
        BomQualProd.setContentAreaFilled(false);
        uJPanelImagem1.add(BomQualProd);
        BomQualProd.setBounds(255, 370, 20, 13);

        BomVarProd.setBackground(new java.awt.Color(161, 211, 176));
        VariedadeProdutos.add(BomVarProd);
        BomVarProd.setForeground(new java.awt.Color(161, 211, 176));
        BomVarProd.setActionCommand("3");
        BomVarProd.setBorder(null);
        BomVarProd.setContentAreaFilled(false);
        uJPanelImagem1.add(BomVarProd);
        BomVarProd.setBounds(255, 350, 20, 13);

        BomPrecos.setBackground(new java.awt.Color(161, 211, 176));
        Precos.add(BomPrecos);
        BomPrecos.setForeground(new java.awt.Color(161, 211, 176));
        BomPrecos.setActionCommand("3");
        BomPrecos.setBorder(null);
        BomPrecos.setContentAreaFilled(false);
        uJPanelImagem1.add(BomPrecos);
        BomPrecos.setBounds(255, 390, 20, 13);

        BomFila.setBackground(new java.awt.Color(161, 211, 176));
        Fila.add(BomFila);
        BomFila.setForeground(new java.awt.Color(161, 211, 176));
        BomFila.setActionCommand("3");
        BomFila.setBorder(null);
        BomFila.setContentAreaFilled(false);
        uJPanelImagem1.add(BomFila);
        BomFila.setBounds(255, 410, 20, 13);

        BomEstacionamento.setBackground(new java.awt.Color(161, 211, 176));
        Estacionamento.add(BomEstacionamento);
        BomEstacionamento.setForeground(new java.awt.Color(161, 211, 176));
        BomEstacionamento.setActionCommand("3");
        BomEstacionamento.setBorder(null);
        BomEstacionamento.setContentAreaFilled(false);
        uJPanelImagem1.add(BomEstacionamento);
        BomEstacionamento.setBounds(255, 430, 20, 13);

        BomAtendCaixa.setBackground(new java.awt.Color(161, 211, 176));
        AtendimentoCaixa.add(BomAtendCaixa);
        BomAtendCaixa.setForeground(new java.awt.Color(161, 211, 176));
        BomAtendCaixa.setActionCommand("3");
        BomAtendCaixa.setBorder(null);
        BomAtendCaixa.setContentAreaFilled(false);
        uJPanelImagem1.add(BomAtendCaixa);
        BomAtendCaixa.setBounds(255, 450, 20, 13);

        BomPadaria.setBackground(new java.awt.Color(161, 211, 176));
        Padaria.add(BomPadaria);
        BomPadaria.setForeground(new java.awt.Color(161, 211, 176));
        BomPadaria.setActionCommand("3");
        BomPadaria.setBorder(null);
        BomPadaria.setContentAreaFilled(false);
        uJPanelImagem1.add(BomPadaria);
        BomPadaria.setBounds(255, 540, 20, 13);

        BomAcougue.setBackground(new java.awt.Color(161, 211, 176));
        Acougue.add(BomAcougue);
        BomAcougue.setForeground(new java.awt.Color(161, 211, 176));
        BomAcougue.setActionCommand("3");
        BomAcougue.setBorder(null);
        BomAcougue.setContentAreaFilled(false);
        uJPanelImagem1.add(BomAcougue);
        BomAcougue.setBounds(255, 520, 20, 13);

        BomFrios.setBackground(new java.awt.Color(161, 211, 176));
        Frios.add(BomFrios);
        BomFrios.setForeground(new java.awt.Color(161, 211, 176));
        BomFrios.setActionCommand("3");
        BomFrios.setBorder(null);
        BomFrios.setContentAreaFilled(false);
        uJPanelImagem1.add(BomFrios);
        BomFrios.setBounds(255, 560, 20, 13);

        BomHortifruti.setBackground(new java.awt.Color(161, 211, 176));
        Hortifruti.add(BomHortifruti);
        BomHortifruti.setForeground(new java.awt.Color(161, 211, 176));
        BomHortifruti.setActionCommand("3");
        BomHortifruti.setBorder(null);
        BomHortifruti.setContentAreaFilled(false);
        uJPanelImagem1.add(BomHortifruti);
        BomHortifruti.setBounds(255, 580, 20, 13);

        BomMercearia.setBackground(new java.awt.Color(161, 211, 176));
        Mercearia.add(BomMercearia);
        BomMercearia.setForeground(new java.awt.Color(161, 211, 176));
        BomMercearia.setActionCommand("3");
        BomMercearia.setBorder(null);
        BomMercearia.setContentAreaFilled(false);
        uJPanelImagem1.add(BomMercearia);
        BomMercearia.setBounds(255, 600, 20, 13);

        BomLanchonete.setBackground(new java.awt.Color(161, 211, 176));
        Lanchonete.add(BomLanchonete);
        BomLanchonete.setForeground(new java.awt.Color(161, 211, 176));
        BomLanchonete.setActionCommand("3");
        BomLanchonete.setBorder(null);
        BomLanchonete.setContentAreaFilled(false);
        uJPanelImagem1.add(BomLanchonete);
        BomLanchonete.setBounds(255, 620, 20, 13);

        BomPegpese.setBackground(new java.awt.Color(161, 211, 176));
        Pegpese.add(BomPegpese);
        BomPegpese.setForeground(new java.awt.Color(161, 211, 176));
        BomPegpese.setActionCommand("3");
        BomPegpese.setBorder(null);
        BomPegpese.setContentAreaFilled(false);
        uJPanelImagem1.add(BomPegpese);
        BomPegpese.setBounds(255, 660, 20, 13);

        RegularAtendimento.setBackground(new java.awt.Color(253, 206, 80));
        Atendimento.add(RegularAtendimento);
        RegularAtendimento.setForeground(new java.awt.Color(253, 206, 80));
        RegularAtendimento.setActionCommand("2");
        RegularAtendimento.setBorder(null);
        RegularAtendimento.setContentAreaFilled(false);
        RegularAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegularAtendimentoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(RegularAtendimento);
        RegularAtendimento.setBounds(310, 330, 20, 13);

        RegularQualProd.setBackground(new java.awt.Color(253, 206, 80));
        QualidadeProdutos.add(RegularQualProd);
        RegularQualProd.setForeground(new java.awt.Color(253, 206, 80));
        RegularQualProd.setActionCommand("2");
        RegularQualProd.setBorder(null);
        RegularQualProd.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularQualProd);
        RegularQualProd.setBounds(310, 370, 20, 13);

        RegularVarProd.setBackground(new java.awt.Color(253, 206, 80));
        VariedadeProdutos.add(RegularVarProd);
        RegularVarProd.setForeground(new java.awt.Color(253, 206, 80));
        RegularVarProd.setActionCommand("2");
        RegularVarProd.setBorder(null);
        RegularVarProd.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularVarProd);
        RegularVarProd.setBounds(310, 350, 20, 13);

        RegularPrecos.setBackground(new java.awt.Color(253, 206, 80));
        Precos.add(RegularPrecos);
        RegularPrecos.setForeground(new java.awt.Color(253, 206, 80));
        RegularPrecos.setActionCommand("2");
        RegularPrecos.setBorder(null);
        RegularPrecos.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularPrecos);
        RegularPrecos.setBounds(310, 390, 20, 13);

        RegularFila.setBackground(new java.awt.Color(253, 206, 80));
        Fila.add(RegularFila);
        RegularFila.setForeground(new java.awt.Color(253, 206, 80));
        RegularFila.setActionCommand("2");
        RegularFila.setBorder(null);
        RegularFila.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularFila);
        RegularFila.setBounds(310, 410, 20, 13);

        RegularEstacionamento.setBackground(new java.awt.Color(253, 206, 80));
        Estacionamento.add(RegularEstacionamento);
        RegularEstacionamento.setForeground(new java.awt.Color(253, 206, 80));
        RegularEstacionamento.setActionCommand("2");
        RegularEstacionamento.setBorder(null);
        RegularEstacionamento.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularEstacionamento);
        RegularEstacionamento.setBounds(310, 430, 20, 13);

        RegularAtendCaixa.setBackground(new java.awt.Color(253, 206, 80));
        AtendimentoCaixa.add(RegularAtendCaixa);
        RegularAtendCaixa.setForeground(new java.awt.Color(253, 206, 80));
        RegularAtendCaixa.setActionCommand("2");
        RegularAtendCaixa.setBorder(null);
        RegularAtendCaixa.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularAtendCaixa);
        RegularAtendCaixa.setBounds(310, 450, 20, 13);

        RegularPadaria.setBackground(new java.awt.Color(253, 206, 80));
        Padaria.add(RegularPadaria);
        RegularPadaria.setForeground(new java.awt.Color(253, 206, 80));
        RegularPadaria.setActionCommand("2");
        RegularPadaria.setBorder(null);
        RegularPadaria.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularPadaria);
        RegularPadaria.setBounds(310, 540, 20, 13);

        RegularAcougue.setBackground(new java.awt.Color(253, 206, 80));
        Acougue.add(RegularAcougue);
        RegularAcougue.setForeground(new java.awt.Color(253, 206, 80));
        RegularAcougue.setActionCommand("2");
        RegularAcougue.setBorder(null);
        RegularAcougue.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularAcougue);
        RegularAcougue.setBounds(310, 520, 20, 13);

        RegularFrios.setBackground(new java.awt.Color(253, 206, 80));
        Frios.add(RegularFrios);
        RegularFrios.setForeground(new java.awt.Color(253, 206, 80));
        RegularFrios.setActionCommand("2");
        RegularFrios.setBorder(null);
        RegularFrios.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularFrios);
        RegularFrios.setBounds(310, 560, 20, 13);

        RegularHortifruti.setBackground(new java.awt.Color(253, 206, 80));
        Hortifruti.add(RegularHortifruti);
        RegularHortifruti.setForeground(new java.awt.Color(253, 206, 80));
        RegularHortifruti.setActionCommand("2");
        RegularHortifruti.setBorder(null);
        RegularHortifruti.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularHortifruti);
        RegularHortifruti.setBounds(310, 580, 20, 13);

        RegularMercearia.setBackground(new java.awt.Color(253, 206, 80));
        Mercearia.add(RegularMercearia);
        RegularMercearia.setForeground(new java.awt.Color(253, 206, 80));
        RegularMercearia.setActionCommand("2");
        RegularMercearia.setBorder(null);
        RegularMercearia.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularMercearia);
        RegularMercearia.setBounds(310, 600, 20, 13);

        RegularLanchonete.setBackground(new java.awt.Color(253, 206, 80));
        Lanchonete.add(RegularLanchonete);
        RegularLanchonete.setForeground(new java.awt.Color(253, 206, 80));
        RegularLanchonete.setActionCommand("2");
        RegularLanchonete.setBorder(null);
        RegularLanchonete.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularLanchonete);
        RegularLanchonete.setBounds(310, 620, 20, 13);

        RegularPegpese.setBackground(new java.awt.Color(253, 206, 80));
        Pegpese.add(RegularPegpese);
        RegularPegpese.setForeground(new java.awt.Color(253, 206, 80));
        RegularPegpese.setActionCommand("2");
        RegularPegpese.setBorder(null);
        RegularPegpese.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularPegpese);
        RegularPegpese.setBounds(310, 660, 20, 13);

        RuimAtendimento.setBackground(new java.awt.Color(237, 59, 72));
        Atendimento.add(RuimAtendimento);
        RuimAtendimento.setForeground(new java.awt.Color(237, 59, 72));
        RuimAtendimento.setActionCommand("1");
        RuimAtendimento.setBorder(null);
        RuimAtendimento.setContentAreaFilled(false);
        RuimAtendimento.setNextFocusableComponent(OtimoVarProd);
        RuimAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuimAtendimentoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(RuimAtendimento);
        RuimAtendimento.setBounds(360, 330, 20, 13);

        RuimQualProd.setBackground(new java.awt.Color(237, 59, 72));
        QualidadeProdutos.add(RuimQualProd);
        RuimQualProd.setForeground(new java.awt.Color(237, 59, 72));
        RuimQualProd.setActionCommand("1");
        RuimQualProd.setBorder(null);
        RuimQualProd.setContentAreaFilled(false);
        RuimQualProd.setNextFocusableComponent(OtimoPrecos);
        uJPanelImagem1.add(RuimQualProd);
        RuimQualProd.setBounds(360, 370, 20, 13);

        RuimVarProd.setBackground(new java.awt.Color(237, 59, 72));
        VariedadeProdutos.add(RuimVarProd);
        RuimVarProd.setForeground(new java.awt.Color(237, 59, 72));
        RuimVarProd.setActionCommand("1");
        RuimVarProd.setBorder(null);
        RuimVarProd.setContentAreaFilled(false);
        RuimVarProd.setNextFocusableComponent(OtimoQualProd);
        uJPanelImagem1.add(RuimVarProd);
        RuimVarProd.setBounds(360, 350, 20, 13);

        RuimPrecos.setBackground(new java.awt.Color(237, 59, 72));
        Precos.add(RuimPrecos);
        RuimPrecos.setForeground(new java.awt.Color(237, 59, 72));
        RuimPrecos.setActionCommand("1");
        RuimPrecos.setBorder(null);
        RuimPrecos.setContentAreaFilled(false);
        RuimPrecos.setNextFocusableComponent(OtimoFila);
        uJPanelImagem1.add(RuimPrecos);
        RuimPrecos.setBounds(360, 390, 20, 13);

        RuimFila.setBackground(new java.awt.Color(237, 59, 72));
        Fila.add(RuimFila);
        RuimFila.setForeground(new java.awt.Color(237, 59, 72));
        RuimFila.setActionCommand("1");
        RuimFila.setBorder(null);
        RuimFila.setContentAreaFilled(false);
        RuimFila.setNextFocusableComponent(OtimoEstacionamento);
        uJPanelImagem1.add(RuimFila);
        RuimFila.setBounds(360, 410, 20, 13);

        RuimEstacionamento.setBackground(new java.awt.Color(237, 59, 72));
        Estacionamento.add(RuimEstacionamento);
        RuimEstacionamento.setForeground(new java.awt.Color(237, 59, 72));
        RuimEstacionamento.setActionCommand("1");
        RuimEstacionamento.setBorder(null);
        RuimEstacionamento.setContentAreaFilled(false);
        RuimEstacionamento.setNextFocusableComponent(OtimoAtendCaixa);
        uJPanelImagem1.add(RuimEstacionamento);
        RuimEstacionamento.setBounds(360, 430, 20, 13);

        RuimAtendCaixa.setBackground(new java.awt.Color(237, 59, 72));
        AtendimentoCaixa.add(RuimAtendCaixa);
        RuimAtendCaixa.setForeground(new java.awt.Color(237, 59, 72));
        RuimAtendCaixa.setActionCommand("1");
        RuimAtendCaixa.setBorder(null);
        RuimAtendCaixa.setContentAreaFilled(false);
        RuimAtendCaixa.setName(""); // NOI18N
        RuimAtendCaixa.setNextFocusableComponent(OtimoAcougue);
        uJPanelImagem1.add(RuimAtendCaixa);
        RuimAtendCaixa.setBounds(360, 450, 20, 13);

        RuimPadaria.setBackground(new java.awt.Color(237, 59, 72));
        Padaria.add(RuimPadaria);
        RuimPadaria.setForeground(new java.awt.Color(237, 59, 72));
        RuimPadaria.setActionCommand("1");
        RuimPadaria.setBorder(null);
        RuimPadaria.setContentAreaFilled(false);
        RuimPadaria.setNextFocusableComponent(OtimoFrios);
        uJPanelImagem1.add(RuimPadaria);
        RuimPadaria.setBounds(360, 540, 20, 13);

        RuimAcougue.setBackground(new java.awt.Color(237, 59, 72));
        Acougue.add(RuimAcougue);
        RuimAcougue.setForeground(new java.awt.Color(237, 59, 72));
        RuimAcougue.setActionCommand("1");
        RuimAcougue.setBorder(null);
        RuimAcougue.setContentAreaFilled(false);
        RuimAcougue.setNextFocusableComponent(OtimoPadaria);
        uJPanelImagem1.add(RuimAcougue);
        RuimAcougue.setBounds(360, 520, 20, 13);

        RuimFrios.setBackground(new java.awt.Color(237, 59, 72));
        Frios.add(RuimFrios);
        RuimFrios.setForeground(new java.awt.Color(237, 59, 72));
        RuimFrios.setActionCommand("1");
        RuimFrios.setBorder(null);
        RuimFrios.setContentAreaFilled(false);
        RuimFrios.setNextFocusableComponent(OtimoHortifruti);
        uJPanelImagem1.add(RuimFrios);
        RuimFrios.setBounds(360, 560, 20, 13);

        RuimHortifruti.setBackground(new java.awt.Color(237, 59, 72));
        Hortifruti.add(RuimHortifruti);
        RuimHortifruti.setForeground(new java.awt.Color(237, 59, 72));
        RuimHortifruti.setActionCommand("1");
        RuimHortifruti.setBorder(null);
        RuimHortifruti.setContentAreaFilled(false);
        RuimHortifruti.setNextFocusableComponent(OtimoMercearia);
        uJPanelImagem1.add(RuimHortifruti);
        RuimHortifruti.setBounds(360, 580, 20, 13);

        RuimMercearia.setBackground(new java.awt.Color(237, 59, 72));
        Mercearia.add(RuimMercearia);
        RuimMercearia.setForeground(new java.awt.Color(237, 59, 72));
        RuimMercearia.setActionCommand("1");
        RuimMercearia.setBorder(null);
        RuimMercearia.setContentAreaFilled(false);
        RuimMercearia.setNextFocusableComponent(OtimoLanchonete);
        uJPanelImagem1.add(RuimMercearia);
        RuimMercearia.setBounds(360, 600, 20, 13);

        RuimLanchonete.setBackground(new java.awt.Color(237, 59, 72));
        Lanchonete.add(RuimLanchonete);
        RuimLanchonete.setForeground(new java.awt.Color(237, 59, 72));
        RuimLanchonete.setActionCommand("1");
        RuimLanchonete.setBorder(null);
        RuimLanchonete.setContentAreaFilled(false);
        RuimLanchonete.setNextFocusableComponent(OtimoAdega);
        uJPanelImagem1.add(RuimLanchonete);
        RuimLanchonete.setBounds(360, 620, 20, 13);

        RuimPegpese.setBackground(new java.awt.Color(237, 59, 72));
        Pegpese.add(RuimPegpese);
        RuimPegpese.setForeground(new java.awt.Color(237, 59, 72));
        RuimPegpese.setActionCommand("1");
        RuimPegpese.setBorder(null);
        RuimPegpese.setContentAreaFilled(false);
        RuimPegpese.setNextFocusableComponent(EncontrouSim);
        uJPanelImagem1.add(RuimPegpese);
        RuimPegpese.setBounds(360, 660, 20, 13);

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(138, 212, 90));
        jLabel28.setText("Se a resposta for \"Não\" diga-nos o que procurava");
        uJPanelImagem1.add(jLabel28);
        jLabel28.setBounds(430, 140, 370, 30);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(138, 212, 90));
        jLabel29.setText("Marque abaixo como você avalia os seguintes itens");
        uJPanelImagem1.add(jLabel29);
        jLabel29.setBounds(20, 265, 380, 30);

        EncontrouNao.setBackground(new java.awt.Color(232, 237, 220));
        EncontrouProduto.add(EncontrouNao);
        EncontrouNao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EncontrouNao.setForeground(new java.awt.Color(232, 237, 220));
        EncontrouNao.setText("Não");
        EncontrouNao.setActionCommand("0");
        EncontrouNao.setBorder(null);
        EncontrouNao.setContentAreaFilled(false);
        EncontrouNao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EncontrouNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncontrouNaoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(EncontrouNao);
        EncontrouNao.setBounds(735, 115, 42, 20);

        EncontrouSim.setBackground(new java.awt.Color(232, 237, 220));
        EncontrouProduto.add(EncontrouSim);
        EncontrouSim.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EncontrouSim.setForeground(new java.awt.Color(232, 237, 220));
        EncontrouSim.setText("Sim");
        EncontrouSim.setActionCommand("1");
        EncontrouSim.setContentAreaFilled(false);
        EncontrouSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EncontrouSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncontrouSimActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(EncontrouSim);
        EncontrouSim.setBounds(685, 115, 47, 20);

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(138, 212, 90));
        jLabel30.setText("Você encontrou o que procurava?");
        uJPanelImagem1.add(jLabel30);
        jLabel30.setBounds(430, 110, 250, 30);

        Comentario.setBackground(new java.awt.Color(230, 255, 226));
        Comentario.setColumns(20);
        Comentario.setLineWrap(true);
        Comentario.setRows(5);
        Comentario.setWrapStyleWord(true);
        Comentario.setNextFocusableComponent(buttonSalvar);
        jScrollPane1.setViewportView(Comentario);

        uJPanelImagem1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 370, 363, 130);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        uJPanelImagem1.add(jSeparator2);
        jSeparator2.setBounds(20, 290, 375, 10);

        AvisarNao.setBackground(new java.awt.Color(232, 237, 220));
        AvisoProduto.add(AvisarNao);
        AvisarNao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AvisarNao.setForeground(new java.awt.Color(232, 237, 220));
        AvisarNao.setText("Não");
        AvisarNao.setActionCommand("0");
        AvisarNao.setContentAreaFilled(false);
        AvisarNao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AvisarNao.setNextFocusableComponent(ComentSugestao);
        uJPanelImagem1.add(AvisarNao);
        AvisarNao.setBounds(737, 278, 50, 20);

        AvisarSim.setBackground(new java.awt.Color(232, 237, 220));
        AvisoProduto.add(AvisarSim);
        AvisarSim.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AvisarSim.setForeground(new java.awt.Color(232, 237, 220));
        AvisarSim.setText("Sim");
        AvisarSim.setActionCommand("1");
        AvisarSim.setContentAreaFilled(false);
        AvisarSim.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AvisarSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvisarSimActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(AvisarSim);
        AvisarSim.setBounds(690, 278, 47, 20);

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(138, 212, 90));
        jLabel31.setText("Podemos avisá-lo(a) quando o produto chegar?");
        uJPanelImagem1.add(jLabel31);
        jLabel31.setBounds(430, 280, 260, 16);

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(138, 212, 90));
        jLabel32.setText("Outros comentários:");
        uJPanelImagem1.add(jLabel32);
        jLabel32.setBounds(430, 305, 380, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        uJPanelImagem1.add(jSeparator3);
        jSeparator3.setBounds(430, 330, 375, 10);

        ComentSugestao.setBackground(new java.awt.Color(232, 237, 220));
        TipoComentario.add(ComentSugestao);
        ComentSugestao.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        ComentSugestao.setForeground(new java.awt.Color(232, 237, 220));
        ComentSugestao.setText("Sugestões");
        ComentSugestao.setActionCommand("1");
        ComentSugestao.setBorder(null);
        ComentSugestao.setContentAreaFilled(false);
        ComentSugestao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ComentSugestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentSugestaoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(ComentSugestao);
        ComentSugestao.setBounds(430, 340, 90, 20);

        ComentReclamacao.setBackground(new java.awt.Color(232, 237, 220));
        TipoComentario.add(ComentReclamacao);
        ComentReclamacao.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        ComentReclamacao.setForeground(new java.awt.Color(232, 237, 220));
        ComentReclamacao.setText("Reclamações");
        ComentReclamacao.setActionCommand("2");
        ComentReclamacao.setBorder(null);
        ComentReclamacao.setContentAreaFilled(false);
        ComentReclamacao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ComentReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentReclamacaoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(ComentReclamacao);
        ComentReclamacao.setBounds(520, 340, 90, 20);

        ComentDuvida.setBackground(new java.awt.Color(232, 237, 220));
        TipoComentario.add(ComentDuvida);
        ComentDuvida.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        ComentDuvida.setForeground(new java.awt.Color(232, 237, 220));
        ComentDuvida.setText("Dúvidas");
        ComentDuvida.setActionCommand("3");
        ComentDuvida.setBorder(null);
        ComentDuvida.setContentAreaFilled(false);
        ComentDuvida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ComentDuvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentDuvidaActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(ComentDuvida);
        ComentDuvida.setBounds(620, 340, 90, 20);

        ProcuraProduto.setBackground(new java.awt.Color(230, 255, 226));
        ProcuraProduto.setColumns(20);
        ProcuraProduto.setLineWrap(true);
        ProcuraProduto.setRows(5);
        ProcuraProduto.setWrapStyleWord(true);
        ProcuraProduto.setNextFocusableComponent(AvisarSim);
        jScrollPane2.setViewportView(ProcuraProduto);

        uJPanelImagem1.add(jScrollPane2);
        jScrollPane2.setBounds(430, 170, 363, 96);

        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/salvar.png"))); // NOI18N
        buttonSalvar.setBorder(null);
        buttonSalvar.setBorderPainted(false);
        buttonSalvar.setContentAreaFilled(false);
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonSalvar);
        buttonSalvar.setBounds(689, 660, 32, 32);

        Unidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Interlagos", "Taboão", "Morumbi", "Pinheiros", "", "Jaguaré", "Bolonha" }));
        Unidade.setSelectedIndex(5);
        uJPanelImagem1.add(Unidade);
        Unidade.setBounds(80, 235, 310, 20);

        AnonimoCheck.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        AnonimoCheck.setForeground(new java.awt.Color(255, 255, 255));
        AnonimoCheck.setText("Anônimo");
        AnonimoCheck.setActionCommand("anon");
        AnonimoCheck.setContentAreaFilled(false);
        AnonimoCheck.setNextFocusableComponent(EmailSim);
        AnonimoCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AnonimoCheckStateChanged(evt);
            }
        });
        AnonimoCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnonimoCheckMouseClicked(evt);
            }
        });
        AnonimoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnonimoCheckActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(AnonimoCheck);
        AnonimoCheck.setBounds(20, 180, 80, 20);

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Adega");
        uJPanelImagem1.add(jLabel33);
        jLabel33.setBounds(20, 640, 150, 16);

        OtimoAdega.setBackground(new java.awt.Color(50, 169, 107));
        Adega.add(OtimoAdega);
        OtimoAdega.setActionCommand("4");
        OtimoAdega.setBorder(null);
        OtimoAdega.setContentAreaFilled(false);
        uJPanelImagem1.add(OtimoAdega);
        OtimoAdega.setBounds(200, 640, 20, 13);

        BomAdega.setBackground(new java.awt.Color(161, 211, 176));
        Adega.add(BomAdega);
        BomAdega.setForeground(new java.awt.Color(161, 211, 176));
        BomAdega.setActionCommand("3");
        BomAdega.setBorder(null);
        BomAdega.setContentAreaFilled(false);
        uJPanelImagem1.add(BomAdega);
        BomAdega.setBounds(255, 640, 20, 13);

        RegularAdega.setBackground(new java.awt.Color(253, 206, 80));
        Adega.add(RegularAdega);
        RegularAdega.setForeground(new java.awt.Color(253, 206, 80));
        RegularAdega.setActionCommand("2");
        RegularAdega.setBorder(null);
        RegularAdega.setContentAreaFilled(false);
        uJPanelImagem1.add(RegularAdega);
        RegularAdega.setBounds(310, 640, 20, 13);

        RuimAdega.setBackground(new java.awt.Color(237, 59, 72));
        Adega.add(RuimAdega);
        RuimAdega.setForeground(new java.awt.Color(237, 59, 72));
        RuimAdega.setActionCommand("1");
        RuimAdega.setBorder(null);
        RuimAdega.setContentAreaFilled(false);
        RuimAdega.setNextFocusableComponent(OtimoPegpese);
        uJPanelImagem1.add(RuimAdega);
        RuimAdega.setBounds(360, 640, 20, 13);

        jLabel34.setForeground(new java.awt.Color(255, 30, 30));
        jLabel34.setText("*");
        uJPanelImagem1.add(jLabel34);
        jLabel34.setBounds(392, 235, 10, 20);

        TextEmail.setBackground(new java.awt.Color(230, 255, 226));
        TextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextEmail.setNextFocusableComponent(TextFone);
        uJPanelImagem1.add(TextEmail);
        TextEmail.setBounds(70, 138, 320, 20);

        Origem_OP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Folheto", "Facebook", "Instagram", "Email/Site", "Telefone", "Presencial" }));
        uJPanelImagem1.add(Origem_OP);
        Origem_OP.setBounds(610, 55, 170, 20);

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(138, 212, 90));
        jLabel35.setText("Nome:");
        uJPanelImagem1.add(jLabel35);
        jLabel35.setBounds(20, 120, 50, 20);

        jLabel36.setForeground(new java.awt.Color(255, 30, 30));
        jLabel36.setText("*");
        uJPanelImagem1.add(jLabel36);
        jLabel36.setBounds(392, 160, 10, 20);

        listaTemasS.setModel(new DefaultListModel());
        listaTemasS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTemasSMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaTemasS);

        uJPanelImagem1.add(jScrollPane3);
        jScrollPane3.setBounds(630, 550, 160, 100);

        listaTemasDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTemasDBMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listaTemasDB);

        uJPanelImagem1.add(jScrollPane4);
        jScrollPane4.setBounds(430, 550, 160, 100);

        buttonEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/esquerda.png"))); // NOI18N
        buttonEsquerda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonEsquerda.setContentAreaFilled(false);
        buttonEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsquerdaActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonEsquerda);
        buttonEsquerda.setBounds(600, 620, 20, 20);

        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/adicionar.png"))); // NOI18N
        buttonAdicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonAdicionar.setContentAreaFilled(false);
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonAdicionar);
        buttonAdicionar.setBounds(600, 560, 20, 20);

        buttonDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/direita.png"))); // NOI18N
        buttonDireita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonDireita.setContentAreaFilled(false);
        buttonDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDireitaActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonDireita);
        buttonDireita.setBounds(600, 590, 20, 20);

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(138, 212, 90));
        jLabel37.setText("Temas");
        uJPanelImagem1.add(jLabel37);
        jLabel37.setBounds(430, 510, 380, 30);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        uJPanelImagem1.add(jSeparator5);
        jSeparator5.setBounds(430, 535, 375, 10);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        uJPanelImagem1.add(jSeparator1);
        jSeparator1.setBounds(418, 100, 4, 605);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        uJPanelImagem1.add(jSeparator4);
        jSeparator4.setBounds(0, 100, 800, 2);

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/limpar.png"))); // NOI18N
        buttonLimpar.setBorderPainted(false);
        buttonLimpar.setContentAreaFilled(false);
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonLimpar);
        buttonLimpar.setBounds(499, 660, 32, 32);

        getContentPane().add(uJPanelImagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
        Inserir.desativarEdit();
        try {
            new MenuFrame().show();
        } catch (IOException ex) {
            Logger.getLogger(InserirFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void TextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataActionPerformed

    private void ComentElogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentElogioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComentElogioActionPerformed

    private void ComentSugestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentSugestaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComentSugestaoActionPerformed

    private void ComentReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComentReclamacaoActionPerformed

    private void ComentDuvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentDuvidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComentDuvidaActionPerformed

    private void AnonimoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnonimoCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnonimoCheckActionPerformed

    private void AnonimoCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AnonimoCheckStateChanged
        
    }//GEN-LAST:event_AnonimoCheckStateChanged

    private void AnonimoCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnonimoCheckMouseClicked
        Inserir.setAnonimo();
    }//GEN-LAST:event_AnonimoCheckMouseClicked

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if(!(TextData.getText().contains(" "))){
            if(Unidade.getSelectedIndex() != 0 && Unidade.getSelectedIndex() != 5 ){
                if(JOptionPane.showConfirmDialog(null, "Deseja inserir estas informações?", "Alerta", JOptionPane.YES_NO_OPTION) == 0){
                    try {
                        Inserir.cliente();
                    } catch (SQLException ex) {
                        Logger.getLogger(InserirFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Erro na inserção ao banco de dados!");
                    }
                    JOptionPane.showMessageDialog(null, "Opinião inserida com sucesso!");
                    this.dispose();
                    Inserir.limparInserir();
                    new InfoFrame().show();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione uma unidade! ");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data Incorreta! ");
        }
        Inserir.desativarEdit();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void EncontrouSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncontrouSimActionPerformed
        
    }//GEN-LAST:event_EncontrouSimActionPerformed

    private void EncontrouNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncontrouNaoActionPerformed
        
    }//GEN-LAST:event_EncontrouNaoActionPerformed

    private void AvisarSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvisarSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvisarSimActionPerformed

    private void EmailNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailNaoActionPerformed
        
    }//GEN-LAST:event_EmailNaoActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        if(listaTemasS.getModel().getSize() < 3)
            Inserir.adicionaNovoTema();
        else
            JOptionPane.showMessageDialog(this,"Adicione somente 3 temas!","Erro ao adicionar tema",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDireitaActionPerformed
        if(listaTemasS.getModel().getSize() < 3)
            Inserir.moverTema("Direita", InserirFrame.listaTemasDB.getSelectedValue());
        else
            JOptionPane.showMessageDialog(this,"Adicione somente 3 temas!","Erro ao adicionar tema",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_buttonDireitaActionPerformed

    private void buttonEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsquerdaActionPerformed
        Inserir.moverTema("Esquerda", InserirFrame.listaTemasS.getSelectedValue());
    }//GEN-LAST:event_buttonEsquerdaActionPerformed

    private void listaTemasDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTemasDBMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            if(listaTemasS.getModel().getSize() < 3)
                Inserir.moverTema("Direita", InserirFrame.listaTemasDB.getSelectedValue());
            else
                JOptionPane.showMessageDialog(this,"Adicione somente 3 temas!","Erro ao adicionar tema",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_listaTemasDBMouseClicked

    private void listaTemasSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTemasSMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Inserir.moverTema("Esquerda", InserirFrame.listaTemasS.getSelectedValue());
        }
    }//GEN-LAST:event_listaTemasSMouseClicked

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        Inserir.fecharInsert();
        Inserir.iniciarInsert();
        Inserir.abrirInsert();
        Inserir.desativarEdit();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void OtimoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtimoAtendimentoActionPerformed
        
    }//GEN-LAST:event_OtimoAtendimentoActionPerformed

    private void EmailSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailSimActionPerformed
        
    }//GEN-LAST:event_EmailSimActionPerformed

    private void BomAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BomAtendimentoActionPerformed
        
    }//GEN-LAST:event_BomAtendimentoActionPerformed

    private void RegularAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegularAtendimentoActionPerformed
        
    }//GEN-LAST:event_RegularAtendimentoActionPerformed

    private void RuimAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuimAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuimAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new InserirFrame().setVisible(true);
            } catch (IOException | SQLException ex) {
                Logger.getLogger(InserirFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Acougue;
    public static javax.swing.ButtonGroup Adega;
    public static javax.swing.JCheckBox AnonimoCheck;
    public static javax.swing.ButtonGroup Atendimento;
    public static javax.swing.ButtonGroup AtendimentoCaixa;
    public static javax.swing.JRadioButton AvisarNao;
    public static javax.swing.JRadioButton AvisarSim;
    public static javax.swing.ButtonGroup AvisoProduto;
    public static javax.swing.JRadioButton BomAcougue;
    public static javax.swing.JRadioButton BomAdega;
    public static javax.swing.JRadioButton BomAtendCaixa;
    public static javax.swing.JRadioButton BomAtendimento;
    public static javax.swing.JRadioButton BomEstacionamento;
    public static javax.swing.JRadioButton BomFila;
    public static javax.swing.JRadioButton BomFrios;
    public static javax.swing.JRadioButton BomHortifruti;
    public static javax.swing.JRadioButton BomLanchonete;
    public static javax.swing.JRadioButton BomMercearia;
    public static javax.swing.JRadioButton BomPadaria;
    public static javax.swing.JRadioButton BomPegpese;
    public static javax.swing.JRadioButton BomPrecos;
    public static javax.swing.JRadioButton BomQualProd;
    public static javax.swing.JRadioButton BomVarProd;
    public static javax.swing.JRadioButton ComentDuvida;
    public static javax.swing.JRadioButton ComentElogio;
    public static javax.swing.JRadioButton ComentReclamacao;
    public static javax.swing.JRadioButton ComentSugestao;
    public static javax.swing.JTextArea Comentario;
    public static javax.swing.JRadioButton EmailNao;
    public static javax.swing.JRadioButton EmailSim;
    public static javax.swing.JRadioButton EncontrouNao;
    public static javax.swing.ButtonGroup EncontrouProduto;
    public static javax.swing.JRadioButton EncontrouSim;
    public static javax.swing.ButtonGroup Estacionamento;
    public static javax.swing.ButtonGroup Fila;
    public static javax.swing.ButtonGroup Frios;
    public static javax.swing.ButtonGroup Hortifruti;
    public static javax.swing.ButtonGroup Lanchonete;
    public static javax.swing.ButtonGroup Mercearia;
    public static javax.swing.JComboBox<String> Origem_OP;
    public static javax.swing.JRadioButton OtimoAcougue;
    public static javax.swing.JRadioButton OtimoAdega;
    public static javax.swing.JRadioButton OtimoAtendCaixa;
    public static javax.swing.JRadioButton OtimoAtendimento;
    public static javax.swing.JRadioButton OtimoEstacionamento;
    public static javax.swing.JRadioButton OtimoFila;
    public static javax.swing.JRadioButton OtimoFrios;
    public static javax.swing.JRadioButton OtimoHortifruti;
    public static javax.swing.JRadioButton OtimoLanchonete;
    public static javax.swing.JRadioButton OtimoMercearia;
    public static javax.swing.JRadioButton OtimoPadaria;
    public static javax.swing.JRadioButton OtimoPegpese;
    public static javax.swing.JRadioButton OtimoPrecos;
    public static javax.swing.JRadioButton OtimoQualProd;
    public static javax.swing.JRadioButton OtimoVarProd;
    public static javax.swing.ButtonGroup Padaria;
    public static javax.swing.ButtonGroup Pegpese;
    public static javax.swing.ButtonGroup Precos;
    public static javax.swing.JTextArea ProcuraProduto;
    public static javax.swing.ButtonGroup QualidadeProdutos;
    public static javax.swing.JRadioButton RegularAcougue;
    public static javax.swing.JRadioButton RegularAdega;
    public static javax.swing.JRadioButton RegularAtendCaixa;
    public static javax.swing.JRadioButton RegularAtendimento;
    public static javax.swing.JRadioButton RegularEstacionamento;
    public static javax.swing.JRadioButton RegularFila;
    public static javax.swing.JRadioButton RegularFrios;
    public static javax.swing.JRadioButton RegularHortifruti;
    public static javax.swing.JRadioButton RegularLanchonete;
    public static javax.swing.JRadioButton RegularMercearia;
    public static javax.swing.JRadioButton RegularPadaria;
    public static javax.swing.JRadioButton RegularPegpese;
    public static javax.swing.JRadioButton RegularPrecos;
    public static javax.swing.JRadioButton RegularQualProd;
    public static javax.swing.JRadioButton RegularVarProd;
    public static javax.swing.JRadioButton RuimAcougue;
    public static javax.swing.JRadioButton RuimAdega;
    public static javax.swing.JRadioButton RuimAtendCaixa;
    public static javax.swing.JRadioButton RuimAtendimento;
    public static javax.swing.JRadioButton RuimEstacionamento;
    public static javax.swing.JRadioButton RuimFila;
    public static javax.swing.JRadioButton RuimFrios;
    public static javax.swing.JRadioButton RuimHortifruti;
    public static javax.swing.JRadioButton RuimLanchonete;
    public static javax.swing.JRadioButton RuimMercearia;
    public static javax.swing.JRadioButton RuimPadaria;
    public static javax.swing.JRadioButton RuimPegpese;
    public static javax.swing.JRadioButton RuimPrecos;
    public static javax.swing.JRadioButton RuimQualProd;
    public static javax.swing.JRadioButton RuimVarProd;
    public static javax.swing.JFormattedTextField TextData;
    public static javax.swing.JTextField TextEmail;
    public static javax.swing.JTextField TextFone;
    public static javax.swing.JTextField TextNome;
    public static javax.swing.ButtonGroup TipoComentario;
    public static javax.swing.JComboBox<String> Unidade;
    public static javax.swing.ButtonGroup VariedadeProdutos;
    public static javax.swing.JButton buttonAdicionar;
    public static javax.swing.JButton buttonDireita;
    public static javax.swing.JButton buttonEsquerda;
    private javax.swing.JButton buttonLimpar;
    public static javax.swing.JButton buttonSalvar;
    public static javax.swing.JButton buttonVoltar;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    public static javax.swing.JLabel jLabel28;
    public static javax.swing.JLabel jLabel29;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel30;
    public static javax.swing.JLabel jLabel31;
    public static javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel jLabel33;
    public static javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel35;
    public static javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel37;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JSeparator jSeparator1;
    public static javax.swing.JSeparator jSeparator2;
    public static javax.swing.JSeparator jSeparator3;
    public static javax.swing.JSeparator jSeparator4;
    public static javax.swing.JSeparator jSeparator5;
    public static javax.swing.JList<String> listaTemasDB;
    public static javax.swing.JList<String> listaTemasS;
    public static javax.swing.ButtonGroup newsfeed;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
