/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goc.Frames;

import goc.Sources.Relatorios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class RelatorioFrame extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioFrame
     */
    public RelatorioFrame() {
        try {
            initComponents();
            String root = new File("..").getCanonicalPath();
            if(!(root.equals("C:\\Users\\Admin\\Documents\\NetBeansProjects"))){
                java.io.File caminho = new java.io.File(root + "\\src\\goc\\img\\sdsds.jpg");
                uJPanelImagem1.setImagem(caminho);
            }
            
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2-20);
        } catch (IOException ex) {
            Logger.getLogger(RelatorioFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frequencia = new javax.swing.ButtonGroup();
        TipoMedia = new javax.swing.ButtonGroup();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        buttonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipoMediaUnidade = new javax.swing.JRadioButton();
        tipoMediaGeral = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        comboAvLoja = new javax.swing.JComboBox<>();
        dataEspecifica = new javax.swing.JComboBox<>();
        tipoMediaAv = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        freqAnual = new javax.swing.JRadioButton();
        freqGeral = new javax.swing.JRadioButton();
        freqMensal = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\GOC\\src\\goc\\img\\sdsds.jpg"));
        uJPanelImagem1.setMinimumSize(new java.awt.Dimension(800, 700));
        uJPanelImagem1.setPreferredSize(new java.awt.Dimension(800, 700));
        uJPanelImagem1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/icoBack.png"))); // NOI18N
        buttonVoltar.setBorderPainted(false);
        buttonVoltar.setContentAreaFilled(false);
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, 48, 48));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G    C");
        uJPanelImagem1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 230, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/logo.png"))); // NOI18N
        uJPanelImagem1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frequência");
        uJPanelImagem1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 137, 140, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mês/Ano");
        uJPanelImagem1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 137, 140, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Média");
        uJPanelImagem1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 137, 140, 30));

        TipoMedia.add(tipoMediaUnidade);
        tipoMediaUnidade.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tipoMediaUnidade.setForeground(new java.awt.Color(255, 255, 255));
        tipoMediaUnidade.setText("Média por Loja");
        tipoMediaUnidade.setActionCommand("3");
        tipoMediaUnidade.setContentAreaFilled(false);
        tipoMediaUnidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoMediaUnidadeItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(tipoMediaUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 210, 140, -1));

        TipoMedia.add(tipoMediaGeral);
        tipoMediaGeral.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tipoMediaGeral.setForeground(new java.awt.Color(255, 255, 255));
        tipoMediaGeral.setSelected(true);
        tipoMediaGeral.setText("Média Geral");
        tipoMediaGeral.setActionCommand("1");
        tipoMediaGeral.setContentAreaFilled(false);
        tipoMediaGeral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoMediaGeralItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(tipoMediaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 165, 140, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avaliação/Loja");
        uJPanelImagem1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 137, 140, 30));

        comboAvLoja.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        comboAvLoja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o x" }));
        comboAvLoja.setEnabled(false);
        uJPanelImagem1.add(comboAvLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 165, 140, 40));

        dataEspecifica.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        dataEspecifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o x" }));
        dataEspecifica.setEnabled(false);
        uJPanelImagem1.add(dataEspecifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 165, 140, 40));

        TipoMedia.add(tipoMediaAv);
        tipoMediaAv.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tipoMediaAv.setForeground(new java.awt.Color(255, 255, 255));
        tipoMediaAv.setText("Média por Avaliação");
        tipoMediaAv.setActionCommand("2");
        tipoMediaAv.setContentAreaFilled(false);
        tipoMediaAv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoMediaAvItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(tipoMediaAv, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 187, 140, -1));

        jLayeredPane1.setBackground(new java.awt.Color(255, 102, 0));
        jLayeredPane1.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        uJPanelImagem1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 250, 704, 265));

        jLayeredPane2.setBackground(new java.awt.Color(204, 0, 0));
        jLayeredPane2.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        uJPanelImagem1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 540, 704, 130));

        Frequencia.add(freqAnual);
        freqAnual.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        freqAnual.setForeground(new java.awt.Color(255, 255, 255));
        freqAnual.setText("Média Anual");
        freqAnual.setActionCommand("3");
        freqAnual.setContentAreaFilled(false);
        freqAnual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                freqAnualItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(freqAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 210, 140, -1));

        Frequencia.add(freqGeral);
        freqGeral.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        freqGeral.setForeground(new java.awt.Color(255, 255, 255));
        freqGeral.setSelected(true);
        freqGeral.setText("Média diária");
        freqGeral.setActionCommand("1");
        freqGeral.setContentAreaFilled(false);
        freqGeral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                freqGeralItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(freqGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 165, 140, -1));

        Frequencia.add(freqMensal);
        freqMensal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        freqMensal.setForeground(new java.awt.Color(255, 255, 255));
        freqMensal.setText("Média Mensal");
        freqMensal.setActionCommand("2");
        freqMensal.setContentAreaFilled(false);
        freqMensal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                freqMensalItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(freqMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 187, 140, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 0, 0));
        jLabel7.setText("NÃO FUNCIONAL");
        uJPanelImagem1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        try {
            new MenuFrame().show();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(InserirFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void freqGeralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_freqGeralItemStateChanged
        Relatorios.carregaFrequencias();
    }//GEN-LAST:event_freqGeralItemStateChanged

    private void freqMensalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_freqMensalItemStateChanged
        Relatorios.carregaFrequencias();
    }//GEN-LAST:event_freqMensalItemStateChanged

    private void freqAnualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_freqAnualItemStateChanged
        Relatorios.carregaFrequencias();
    }//GEN-LAST:event_freqAnualItemStateChanged

    private void tipoMediaGeralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoMediaGeralItemStateChanged
        Relatorios.carregaTipoMedia();
    }//GEN-LAST:event_tipoMediaGeralItemStateChanged

    private void tipoMediaAvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoMediaAvItemStateChanged
        Relatorios.carregaTipoMedia();
    }//GEN-LAST:event_tipoMediaAvItemStateChanged

    private void tipoMediaUnidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoMediaUnidadeItemStateChanged
        Relatorios.carregaTipoMedia();
    }//GEN-LAST:event_tipoMediaUnidadeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Frequencia;
    public static javax.swing.ButtonGroup TipoMedia;
    public static javax.swing.JButton buttonVoltar;
    public static javax.swing.JComboBox<String> comboAvLoja;
    public static javax.swing.JComboBox<String> dataEspecifica;
    public static javax.swing.JRadioButton freqAnual;
    public static javax.swing.JRadioButton freqGeral;
    public static javax.swing.JRadioButton freqMensal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLayeredPane jLayeredPane1;
    public static javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JRadioButton tipoMediaAv;
    public static javax.swing.JRadioButton tipoMediaGeral;
    public static javax.swing.JRadioButton tipoMediaUnidade;
    public static componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
