/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goc.Frames;

import goc.Sources.View;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Admin
 */
public class ViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewFrame
     * @throws java.io.IOException
     */
    public ViewFrame() throws IOException, ParseException {
        initComponents();
        String root = new File("..").getCanonicalPath();
        
        buttonVisualizar.setVisible(false);
        buttonExcluir.setVisible(false);
        buttonEditar.setVisible(false);
        if(!(root.equals("C:\\Users\\Admin\\Documents\\NetBeansProjects"))){
            java.io.File caminho = new java.io.File(root + "\\src\\goc\\img\\sdsds.jpg");
            uJPanelImagem1.setImagem(caminho);
        }
        
        View.atualizarDados();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2-20);
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (jTable1.getSelectedRow() > -1) {
                    View.verificaSelecao();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroComentarios = new javax.swing.ButtonGroup();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonVisualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Unidade = new javax.swing.JComboBox<>();
        labelQuantidade = new javax.swing.JLabel();
        Origem_OP = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Mes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Ano = new javax.swing.JComboBox<>();
        radioSugestoes = new javax.swing.JRadioButton();
        radioSemComentarios = new javax.swing.JRadioButton();
        radioElogios = new javax.swing.JRadioButton();
        radioTodos = new javax.swing.JRadioButton();
        radioDuvidas = new javax.swing.JRadioButton();
        radioReclamacoes = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Temas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        opiniao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        prodProcurado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\GOC\\src\\goc\\img\\sdsds.jpg"));
        uJPanelImagem1.setMaximumSize(new java.awt.Dimension(800, 600));
        uJPanelImagem1.setMinimumSize(new java.awt.Dimension(800, 600));
        uJPanelImagem1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G    C");
        uJPanelImagem1.add(jLabel1);
        jLabel1.setBounds(330, 20, 170, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/logo.png"))); // NOI18N
        uJPanelImagem1.add(jLabel3);
        jLabel3.setBounds(390, 10, 60, 81);

        buttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/icoBack.png"))); // NOI18N
        buttonVoltar.setBorderPainted(false);
        buttonVoltar.setContentAreaFilled(false);
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonVoltar);
        buttonVoltar.setBounds(10, 35, 48, 48);

        jTable1.setAutoCreateRowSorter(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Loja", "Cliente", "Origem da Opinião", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jTable1.setRowSelectionAllowed(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTable1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        uJPanelImagem1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 280, 760, 240);

        buttonVisualizar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        buttonVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/visualizar.png"))); // NOI18N
        buttonVisualizar.setBorderPainted(false);
        buttonVisualizar.setContentAreaFilled(false);
        buttonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonVisualizar);
        buttonVisualizar.setBounds(376, 540, 48, 48);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unidade");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel2);
        jLabel2.setBounds(10, 120, 140, 17);

        Unidade.setBackground(new java.awt.Color(204, 255, 204));
        Unidade.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Unidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas as Unidades", "Interlagos", "Taboão", "Morumbi", "Pinheiros", " ", "Jaguaré", "Bolonha" }));
        Unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadeActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(Unidade);
        Unidade.setBounds(10, 140, 140, 20);

        labelQuantidade.setBackground(new java.awt.Color(204, 255, 204));
        labelQuantidade.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelQuantidade.setForeground(new java.awt.Color(204, 255, 204));
        labelQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelQuantidade.setText("x opiniões encontradas");
        labelQuantidade.setFocusable(false);
        labelQuantidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(labelQuantidade);
        labelQuantidade.setBounds(580, 520, 200, 25);

        Origem_OP.setBackground(new java.awt.Color(204, 255, 204));
        Origem_OP.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Origem_OP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas as Origens", "Folhinha", "Facebook", "Instagram", "Email/Site", "Telefone", "Presencial" }));
        Origem_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origem_OPActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(Origem_OP);
        Origem_OP.setBounds(170, 140, 140, 20);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mês");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel5);
        jLabel5.setBounds(490, 120, 140, 17);

        Mes.setBackground(new java.awt.Color(204, 255, 204));
        Mes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos os meses", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        Mes.setEnabled(false);
        Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(Mes);
        Mes.setBounds(490, 140, 140, 20);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ano");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel6);
        jLabel6.setBounds(330, 120, 140, 17);

        Ano.setBackground(new java.awt.Color(204, 255, 204));
        Ano.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desde 2014", "2015", "2016", "2017" }));
        Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(Ano);
        Ano.setBounds(330, 140, 140, 20);

        radioSugestoes.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioSugestoes);
        radioSugestoes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioSugestoes.setForeground(new java.awt.Color(204, 255, 204));
        radioSugestoes.setText("Sugestões");
        radioSugestoes.setToolTipText("");
        radioSugestoes.setActionCommand("1");
        radioSugestoes.setContentAreaFilled(false);
        radioSugestoes.setName("3"); // NOI18N
        radioSugestoes.setNextFocusableComponent(radioReclamacoes);
        radioSugestoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioSugestoesItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(radioSugestoes);
        radioSugestoes.setBounds(360, 175, 90, 23);

        radioSemComentarios.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioSemComentarios);
        radioSemComentarios.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioSemComentarios.setForeground(new java.awt.Color(204, 255, 204));
        radioSemComentarios.setText("Sem comentários");
        radioSemComentarios.setToolTipText("");
        radioSemComentarios.setActionCommand("0");
        radioSemComentarios.setContentAreaFilled(false);
        radioSemComentarios.setName("2"); // NOI18N
        radioSemComentarios.setNextFocusableComponent(radioSugestoes);
        radioSemComentarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioSemComentariosItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(radioSemComentarios);
        radioSemComentarios.setBounds(240, 175, 120, 23);

        radioElogios.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioElogios);
        radioElogios.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioElogios.setForeground(new java.awt.Color(204, 255, 204));
        radioElogios.setText("Elogios");
        radioElogios.setToolTipText("");
        radioElogios.setActionCommand("4");
        radioElogios.setContentAreaFilled(false);
        radioElogios.setName("6"); // NOI18N
        radioElogios.setNextFocusableComponent(radioTodos);
        radioElogios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioElogiosItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(radioElogios);
        radioElogios.setBounds(630, 175, 70, 23);

        radioTodos.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioTodos);
        radioTodos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioTodos.setForeground(new java.awt.Color(204, 255, 204));
        radioTodos.setSelected(true);
        radioTodos.setText("Todas as opiniões");
        radioTodos.setToolTipText("");
        radioTodos.setActionCommand("5");
        radioTodos.setContentAreaFilled(false);
        radioTodos.setName("1"); // NOI18N
        radioTodos.setNextFocusableComponent(radioSemComentarios);
        radioTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioTodosItemStateChanged(evt);
            }
        });
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(radioTodos);
        radioTodos.setBounds(110, 175, 130, 23);

        radioDuvidas.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioDuvidas);
        radioDuvidas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioDuvidas.setForeground(new java.awt.Color(204, 255, 204));
        radioDuvidas.setText("Dúvidas");
        radioDuvidas.setToolTipText("");
        radioDuvidas.setActionCommand("3");
        radioDuvidas.setContentAreaFilled(false);
        radioDuvidas.setName("5"); // NOI18N
        radioDuvidas.setNextFocusableComponent(radioElogios);
        radioDuvidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioDuvidasItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(radioDuvidas);
        radioDuvidas.setBounds(550, 175, 80, 23);

        radioReclamacoes.setBackground(new java.awt.Color(204, 255, 204));
        filtroComentarios.add(radioReclamacoes);
        radioReclamacoes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radioReclamacoes.setForeground(new java.awt.Color(204, 255, 204));
        radioReclamacoes.setText("Reclamações");
        radioReclamacoes.setToolTipText("");
        radioReclamacoes.setActionCommand("2");
        radioReclamacoes.setContentAreaFilled(false);
        radioReclamacoes.setName("4"); // NOI18N
        radioReclamacoes.setNextFocusableComponent(radioDuvidas);
        radioReclamacoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioReclamacoesItemStateChanged(evt);
            }
        });
        uJPanelImagem1.add(radioReclamacoes);
        radioReclamacoes.setBounds(450, 175, 100, 23);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tema");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel4);
        jLabel4.setBounds(650, 120, 140, 17);

        Temas.setBackground(new java.awt.Color(204, 255, 204));
        Temas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Temas.setModel(View.populateTemas());
        Temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemasActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(Temas);
        Temas.setBounds(650, 140, 140, 20);

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Origem da Opinião");
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel9);
        jLabel9.setBounds(170, 120, 140, 17);

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nome do Cliente");
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel10);
        jLabel10.setBounds(20, 215, 250, 17);

        nomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeClienteKeyTyped(evt);
            }
        });
        uJPanelImagem1.add(nomeCliente);
        nomeCliente.setBounds(20, 235, 250, 20);

        opiniao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opiniaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opiniaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                opiniaoKeyTyped(evt);
            }
        });
        uJPanelImagem1.add(opiniao);
        opiniao.setBounds(275, 235, 250, 20);

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Produto Procurado");
        jLabel12.setFocusable(false);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel12);
        jLabel12.setBounds(530, 215, 250, 17);

        prodProcurado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prodProcuradoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodProcuradoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodProcuradoKeyTyped(evt);
            }
        });
        uJPanelImagem1.add(prodProcurado);
        prodProcurado.setBounds(530, 235, 250, 20);

        jLabel13.setBackground(new java.awt.Color(204, 255, 204));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Conteúdo da Opinião");
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uJPanelImagem1.add(jLabel13);
        jLabel13.setBounds(275, 215, 250, 17);

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/limpar.png"))); // NOI18N
        buttonLimpar.setToolTipText("Limpar Filtros");
        buttonLimpar.setBorder(null);
        buttonLimpar.setContentAreaFilled(false);
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonLimpar);
        buttonLimpar.setBounds(740, 40, 38, 38);

        buttonExcluir.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/deletar.png"))); // NOI18N
        buttonExcluir.setBorderPainted(false);
        buttonExcluir.setContentAreaFilled(false);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonExcluir);
        buttonExcluir.setBounds(474, 540, 48, 48);

        buttonEditar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goc/img/editar.png"))); // NOI18N
        buttonEditar.setBorderPainted(false);
        buttonEditar.setContentAreaFilled(false);
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        uJPanelImagem1.add(buttonEditar);
        buttonEditar.setBounds(278, 540, 48, 48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        View.fecharView();
        try {
            new MenuFrame().show();
        } catch (IOException ex) {
            Logger.getLogger(InserirFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void UnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadeActionPerformed
        View.atualizarDados();
    }//GEN-LAST:event_UnidadeActionPerformed

    private void MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesActionPerformed
        View.atualizarDados();
    }//GEN-LAST:event_MesActionPerformed

    private void AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoActionPerformed
        View.atualizarDados();
        Mes.setEnabled(Ano.getSelectedIndex()!=0);
    }//GEN-LAST:event_AnoActionPerformed

    private void radioSugestoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioSugestoesItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioSugestoesItemStateChanged

    private void radioSemComentariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioSemComentariosItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioSemComentariosItemStateChanged

    private void radioElogiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioElogiosItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioElogiosItemStateChanged

    private void radioTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioTodosItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioTodosItemStateChanged

    private void radioDuvidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioDuvidasItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioDuvidasItemStateChanged

    private void radioReclamacoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioReclamacoesItemStateChanged
        View.atualizarDados();
    }//GEN-LAST:event_radioReclamacoesItemStateChanged

    private void jTable1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1CaretPositionChanged
        View.verificaSelecao();
    }//GEN-LAST:event_jTable1CaretPositionChanged

    private void buttonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarActionPerformed
        View.setOpiniao(View.verificaSelecao());
        new InfoFrame().setVisible(true);
        View.fecharView();
    }//GEN-LAST:event_buttonVisualizarActionPerformed

    private void Origem_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origem_OPActionPerformed
        View.atualizarDados();
    }//GEN-LAST:event_Origem_OPActionPerformed

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTodosActionPerformed

    private void TemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemasActionPerformed
        View.atualizarDados();
    }//GEN-LAST:event_TemasActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            View.setOpiniao(View.verificaSelecao());
            new InfoFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void nomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteKeyTyped
        
    }//GEN-LAST:event_nomeClienteKeyTyped

    private void opiniaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opiniaoKeyTyped
        
    }//GEN-LAST:event_opiniaoKeyTyped

    private void prodProcuradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodProcuradoKeyTyped
        
    }//GEN-LAST:event_prodProcuradoKeyTyped

    private void nomeClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteKeyPressed
        
    }//GEN-LAST:event_nomeClienteKeyPressed

    private void opiniaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opiniaoKeyPressed
        
    }//GEN-LAST:event_opiniaoKeyPressed

    private void prodProcuradoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodProcuradoKeyPressed
        
    }//GEN-LAST:event_prodProcuradoKeyPressed

    private void nomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteKeyReleased
        View.atualizarDados();
    }//GEN-LAST:event_nomeClienteKeyReleased

    private void opiniaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opiniaoKeyReleased
        View.atualizarDados();
    }//GEN-LAST:event_opiniaoKeyReleased

    private void prodProcuradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodProcuradoKeyReleased
        View.atualizarDados();
    }//GEN-LAST:event_prodProcuradoKeyReleased

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        View.fecharView();
        View.iniciarView();
        View.abrirView();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        View.deletarOpiniao();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        View.editarOpiniao();
        View.fecharView();
    }//GEN-LAST:event_buttonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ViewFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ViewFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(ViewFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Ano;
    public static javax.swing.JComboBox<String> Mes;
    public static javax.swing.JComboBox<String> Origem_OP;
    public static javax.swing.JComboBox<String> Temas;
    public static javax.swing.JComboBox<String> Unidade;
    public static javax.swing.JButton buttonEditar;
    public static javax.swing.JButton buttonExcluir;
    public static javax.swing.JButton buttonLimpar;
    public static javax.swing.JButton buttonVisualizar;
    public static javax.swing.JButton buttonVoltar;
    public static javax.swing.ButtonGroup filtroComentarios;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JLabel labelQuantidade;
    public static javax.swing.JTextField nomeCliente;
    public static javax.swing.JTextField opiniao;
    public static javax.swing.JTextField prodProcurado;
    public static javax.swing.JRadioButton radioDuvidas;
    public static javax.swing.JRadioButton radioElogios;
    public static javax.swing.JRadioButton radioReclamacoes;
    public static javax.swing.JRadioButton radioSemComentarios;
    public static javax.swing.JRadioButton radioSugestoes;
    public static javax.swing.JRadioButton radioTodos;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
